image: docker:latest
services:
  - docker:dind

stages:
  - build-docker
  - test-ci

variables:
  CONTAINER_IMAGE: registry.worldiety.net/flahde/dind-java:${CI_COMMIT_SHORT_SHA}


build-docker:
  stage: build-docker
  tags:
    - docker-build-runner
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} registry.worldiety.net/flahde/dind-java:latest
    - docker push ${CONTAINER_IMAGE}

test-ci:
  image: ${CONTAINER_IMAGE}
  stage: test-ci
  tags:
    - docker-build-runner
  script:
    - java -version
    - docker run --rm hello-world
